// One recording per kana sound, keyed by its standard romaji. Generated from
// assets/audio/kana/ (see SOURCES.md there). Katakana and hiragana share a sound, so they
// share a clip. Metro needs every require written out in full, so this list can't be a loop.
import type { AudioSource } from 'expo-audio';

export const CLIPS: Readonly<Record<string, AudioSource>> = {
  a: require('../../assets/audio/kana/a.mp3'),
  i: require('../../assets/audio/kana/i.mp3'),
  u: require('../../assets/audio/kana/u.mp3'),
  e: require('../../assets/audio/kana/e.mp3'),
  o: require('../../assets/audio/kana/o.mp3'),
  ka: require('../../assets/audio/kana/ka.mp3'),
  ki: require('../../assets/audio/kana/ki.mp3'),
  ku: require('../../assets/audio/kana/ku.mp3'),
  ke: require('../../assets/audio/kana/ke.mp3'),
  ko: require('../../assets/audio/kana/ko.mp3'),
  sa: require('../../assets/audio/kana/sa.mp3'),
  shi: require('../../assets/audio/kana/shi.mp3'),
  su: require('../../assets/audio/kana/su.mp3'),
  se: require('../../assets/audio/kana/se.mp3'),
  so: require('../../assets/audio/kana/so.mp3'),
  ta: require('../../assets/audio/kana/ta.mp3'),
  chi: require('../../assets/audio/kana/chi.mp3'),
  tsu: require('../../assets/audio/kana/tsu.mp3'),
  te: require('../../assets/audio/kana/te.mp3'),
  to: require('../../assets/audio/kana/to.mp3'),
  na: require('../../assets/audio/kana/na.mp3'),
  ni: require('../../assets/audio/kana/ni.mp3'),
  nu: require('../../assets/audio/kana/nu.mp3'),
  ne: require('../../assets/audio/kana/ne.mp3'),
  no: require('../../assets/audio/kana/no.mp3'),
  ha: require('../../assets/audio/kana/ha.mp3'),
  hi: require('../../assets/audio/kana/hi.mp3'),
  fu: require('../../assets/audio/kana/fu.mp3'),
  he: require('../../assets/audio/kana/he.mp3'),
  ho: require('../../assets/audio/kana/ho.mp3'),
  ma: require('../../assets/audio/kana/ma.mp3'),
  mi: require('../../assets/audio/kana/mi.mp3'),
  mu: require('../../assets/audio/kana/mu.mp3'),
  me: require('../../assets/audio/kana/me.mp3'),
  mo: require('../../assets/audio/kana/mo.mp3'),
  ya: require('../../assets/audio/kana/ya.mp3'),
  yu: require('../../assets/audio/kana/yu.mp3'),
  yo: require('../../assets/audio/kana/yo.mp3'),
  ra: require('../../assets/audio/kana/ra.mp3'),
  ri: require('../../assets/audio/kana/ri.mp3'),
  ru: require('../../assets/audio/kana/ru.mp3'),
  re: require('../../assets/audio/kana/re.mp3'),
  ro: require('../../assets/audio/kana/ro.mp3'),
  wa: require('../../assets/audio/kana/wa.mp3'),
  wo: require('../../assets/audio/kana/wo.mp3'),
  n: require('../../assets/audio/kana/n.mp3'),
};
