// A memory tip for every kana: a picture of its shape tied to its sound.
// These are first drafts, meant to be rewritten in the app's own voice.

const KANA_TIPS: Readonly<Record<string, string>> = {
  // Hiragana
  あ: 'A cross with a big loop swung around it, like an acrobat mid-flip shouting "ah!": a.',
  い: 'Two short strokes standing side by side, like two eels: i.',
  う: 'A small dash over a hooked back, like someone doubled over going "ooh": u.',
  え: 'A dash over a zig-zag that kicks out at the bottom, like someone tripping and saying "eh?": e.',
  お: 'Like あ with an extra dash flying off to the right, an "oh!" of surprise: o.',
  か: 'A bent blade with a small stroke beside it, like a karate chop: ka.',
  き: 'Two crossbars on a stem with a curl at the bottom, like an old key: ki.',
  く: 'One sharp bend, like a cuckoo opening its beak: ku.',
  け: 'A tall line with a cross beside it, like a keg with a tap: ke.',
  こ: 'Two short strokes stacked, like two coins lying flat: ko.',
  さ: 'A crossbar and a stroke through it, with a curve at the bottom like a hanging saddle: sa.',
  し: 'One stroke that dips and curves up, like a fishing hook. She went fishing: shi.',
  す: 'A crossbar with a stroke that loops once and drops, like a swing: su.',
  せ: 'A crossbar on two posts, one bending back underneath, like a setting sun behind a fence: se.',
  そ: 'A zig, a zag and a long sweep, like a thread being sewn: so.',
  た: 'A cross next to two short strokes, like a table with two plates: ta.',
  ち: 'A crossbar with a curve bulging right, like the bottom of a 5 puffing out its cheek: chi.',
  つ: 'One wave curling over to the left, like a small tsunami: tsu.',
  て: 'A crossbar with a stroke curving down and back, like a tail hanging off a table: te.',
  と: 'A short tick leaning on a curve, like a splinter in a toe: to.',
  な: 'A cross on the left and a loop on the right, like a nun kneeling in prayer: na.',
  に: 'A tall line with two short strokes beside it, like a knee next to two steps: ni.',
  ぬ: 'Two crossing strokes ending in a little loop, like noodles curling on chopsticks: nu.',
  ね: 'A stem with a curve that ends in a loop, like a cat curling its tail. Neko means cat: ne.',
  の: 'One big swirl, like the circle on a "no entry" sign: no.',
  は: 'A tall line with a cross and a loop, like someone holding their belly laughing "ha!": ha.',
  ひ: 'One wide curve, like a big grin going "hee hee": hi.',
  ふ: 'Four strokes around a peak, like Mount Fuji with clouds: fu.',
  へ: 'A simple peak, like a hill that makes you go "heh" when you climb it: he.',
  ほ: 'Like は with an extra bar on top, a taller laugh: "ho ho!": ho.',
  ま: 'Two crossbars on a stem that loops at the bottom, like a mast with a rope: ma.',
  み: 'A loop with a tail crossing it, like the number 21. Me at twenty-one: mi.',
  む: 'A stroke with a loop and a little dash, like a cow turning its head to moo: mu.',
  め: 'Like ぬ but with no loop, an open eye. Me means eye: me.',
  も: 'A fishing hook with two lines across it, for catching more fish: mo.',
  や: 'A curved horn with a line through it and a dot, like a yak: ya.',
  ゆ: 'A loop with a line through the middle, like a U-turn: yu.',
  よ: 'A cross with a loop at the bottom, like a yo-yo on its string: yo.',
  ら: 'A dash over a curve, like a rabbit with one ear up: ra.',
  り: 'Two strokes, the right one longer, like reeds by a river: ri.',
  る: 'A zig-zag that ends in a loop, like a road that loops back home. Route: ru.',
  れ: 'A stem with a tail kicking out to the right, like a ray swimming off: re.',
  ろ: 'Like る with no loop at the end, an open road: ro.',
  わ: 'A stem with a curve that rounds back in, like a duck waddling: wa.',
  を: 'A figure pulling back on reins, "whoa!": wo.',
  ん: 'Like a quickly written lowercase n with a tail: n.',
  // Hiragana dakuten and handakuten
  が: 'か with dakuten, the two little strokes (゛) that voice a sound: ka becomes ga.',
  ぎ: 'き with dakuten: ki becomes gi.',
  ぐ: 'く with dakuten: ku becomes gu.',
  げ: 'け with dakuten: ke becomes ge.',
  ご: 'こ with dakuten: ko becomes go.',
  ざ: 'さ with dakuten: sa becomes za.',
  じ: 'し with dakuten: shi becomes ji.',
  ず: 'す with dakuten: su becomes zu.',
  ぜ: 'せ with dakuten: se becomes ze.',
  ぞ: 'そ with dakuten: so becomes zo.',
  だ: 'た with dakuten: ta becomes da.',
  ぢ: 'ち with dakuten: chi becomes ji, the same sound as じ. It\'s rare: じ is the usual way to write ji.',
  づ: 'つ with dakuten: tsu becomes zu, the same sound as ず. It\'s rare: ず is the usual way to write zu.',
  で: 'て with dakuten: te becomes de.',
  ど: 'と with dakuten: to becomes do.',
  ば: 'は with dakuten: ha becomes ba.',
  び: 'ひ with dakuten: hi becomes bi.',
  ぶ: 'ふ with dakuten: fu becomes bu.',
  べ: 'へ with dakuten: he becomes be.',
  ぼ: 'ほ with dakuten: ho becomes bo.',
  ぱ: 'は with handakuten, the little circle (゜) that turns h into p: ha becomes pa.',
  ぴ: 'ひ with the little circle: hi becomes pi.',
  ぷ: 'ふ with the little circle: fu becomes pu.',
  ぺ: 'へ with the little circle: he becomes pe.',
  ぽ: 'ほ with the little circle: ho becomes po.',
  // Hiragana yōon
  きゃ: 'き with a small ゃ: ki and ya run together into one sound, kya.',
  きゅ: 'き with a small ゅ: ki and yu run together into one sound, kyu.',
  きょ: 'き with a small ょ: ki and yo run together into one sound, kyo.',
  しゃ: 'し with a small ゃ: shi and ya run together into one sound, sha.',
  しゅ: 'し with a small ゅ: shi and yu run together into one sound, shu.',
  しょ: 'し with a small ょ: shi and yo run together into one sound, sho.',
  ちゃ: 'ち with a small ゃ: chi and ya run together into one sound, cha.',
  ちゅ: 'ち with a small ゅ: chi and yu run together into one sound, chu.',
  ちょ: 'ち with a small ょ: chi and yo run together into one sound, cho.',
  にゃ: 'に with a small ゃ: ni and ya run together into one sound, nya.',
  にゅ: 'に with a small ゅ: ni and yu run together into one sound, nyu.',
  にょ: 'に with a small ょ: ni and yo run together into one sound, nyo.',
  ひゃ: 'ひ with a small ゃ: hi and ya run together into one sound, hya.',
  ひゅ: 'ひ with a small ゅ: hi and yu run together into one sound, hyu.',
  ひょ: 'ひ with a small ょ: hi and yo run together into one sound, hyo.',
  みゃ: 'み with a small ゃ: mi and ya run together into one sound, mya.',
  みゅ: 'み with a small ゅ: mi and yu run together into one sound, myu.',
  みょ: 'み with a small ょ: mi and yo run together into one sound, myo.',
  りゃ: 'り with a small ゃ: ri and ya run together into one sound, rya.',
  りゅ: 'り with a small ゅ: ri and yu run together into one sound, ryu.',
  りょ: 'り with a small ょ: ri and yo run together into one sound, ryo.',
  ぎゃ: 'ぎ with a small ゃ: gi and ya run together into one sound, gya.',
  ぎゅ: 'ぎ with a small ゅ: gi and yu run together into one sound, gyu.',
  ぎょ: 'ぎ with a small ょ: gi and yo run together into one sound, gyo.',
  じゃ: 'じ with a small ゃ: ji and ya run together into one sound, ja.',
  じゅ: 'じ with a small ゅ: ji and yu run together into one sound, ju.',
  じょ: 'じ with a small ょ: ji and yo run together into one sound, jo.',
  びゃ: 'び with a small ゃ: bi and ya run together into one sound, bya.',
  びゅ: 'び with a small ゅ: bi and yu run together into one sound, byu.',
  びょ: 'び with a small ょ: bi and yo run together into one sound, byo.',
  ぴゃ: 'ぴ with a small ゃ: pi and ya run together into one sound, pya.',
  ぴゅ: 'ぴ with a small ゅ: pi and yu run together into one sound, pyu.',
  ぴょ: 'ぴ with a small ょ: pi and yo run together into one sound, pyo.',

  // Katakana
  ア: 'A short stroke hooked over a long one, like an axe: a.',
  イ: 'A slash leaning on a pole, like an easel: i.',
  ウ: 'Like う with a roof on top, a hut to say "ooh" in: u.',
  エ: 'A steel girder, like the edge of an elevator shaft: e.',
  オ: 'A cross with a slash, like an oar in the water: o.',
  カ: 'Like か without its extra stroke, a karate chop: ka.',
  キ: 'Two crossbars on a stem, like a key: ki.',
  ク: 'A short tick and a long bent stroke, like a cuckoo bird\'s beak: ku.',
  ケ: 'A small slash, a crossbar and a long leg, like a K leaning over: ke.',
  コ: 'Three sides of a box, like a corner: ko.',
  サ: 'A crossbar on two posts, one bending down, like a saw: sa.',
  シ: 'Two short strokes on the left and a long one sweeping up, like a smile turned sideways. She smiles: shi.',
  ス: 'A bent stroke with a leg kicking out, like someone striding in a suit: su.',
  セ: 'Like せ with one post taken away: se.',
  ソ: 'A short stroke on top and a long one falling down, like sewing a stitch downward: so.',
  タ: 'Like ク with an extra line inside, a table set up in a tent: ta.',
  チ: 'A slanted cap over a cross, like a cheerleader\'s pom-pom stick: chi.',
  ツ: 'Short strokes on top and a long one sweeping down, like a tsunami crashing: tsu.',
  テ: 'A T with an extra bar on top, like a telephone pole: te.',
  ト: 'A pole with one branch, like a totem pole: to.',
  ナ: 'A cross whose down stroke bends left, like a knife: na.',
  ニ: 'Two lines, like two knees. 二 is also the number two: ni.',
  ヌ: 'Like フ with a small slash across it, noodles held by chopsticks: nu.',
  ネ: 'A little roof over a cross, like a net on a post: ne.',
  ノ: 'One slash, a firm "no!": no.',
  ハ: 'Two strokes spreading apart, like an open mouth laughing "ha!": ha.',
  ヒ: 'A line with a hook curving back, like the heel of a shoe: hi.',
  フ: 'One hooked stroke, like the slope of Mount Fuji: fu.',
  ヘ: 'The same peak as へ, a hill: he.',
  ホ: 'A cross with two little legs, like a holy cross on a stand: ho.',
  マ: 'A stroke folding back with a tick inside, like a mama bird\'s wing: ma.',
  ミ: 'Three short lines, like three mice asleep in a row: mi.',
  ム: 'A triangle with a tail, like a cow\'s nose: mu.',
  メ: 'Two crossing strokes, like an X marks the spot. Meet me here: me.',
  モ: 'Like も without the curl, two lines on a hook for more fish: mo.',
  ヤ: 'Like や without the dot, a yak\'s horn: ya.',
  ユ: 'A U-shaped hook on a base, like a U-turn: yu.',
  ヨ: 'A backward E, like a yo-yo trick going the wrong way: yo.',
  ラ: 'A dash over a bent stroke, like a rabbit ear: ra.',
  リ: 'Like り, two reeds: ri.',
  ル: 'Two legs, the right one kicking up, like a runner: ru.',
  レ: 'One stroke down and a flick up to the right, like a check mark on a report: re.',
  ロ: 'A box, like a mouth wide open to roar: ro.',
  ワ: 'A roof curving down, like a wall of water: wa.',
  ヲ: 'Like フ with a bar across it, a horse pulling up: "whoa!": wo.',
  ン: 'A short stroke on the left and a long one sweeping up, like a nose sniffing upward: n.',
  // Katakana dakuten and handakuten
  ガ: 'カ with dakuten, the two little strokes (゛) that voice a sound: ka becomes ga.',
  ギ: 'キ with dakuten: ki becomes gi.',
  グ: 'ク with dakuten: ku becomes gu.',
  ゲ: 'ケ with dakuten: ke becomes ge.',
  ゴ: 'コ with dakuten: ko becomes go.',
  ザ: 'サ with dakuten: sa becomes za.',
  ジ: 'シ with dakuten: shi becomes ji.',
  ズ: 'ス with dakuten: su becomes zu.',
  ゼ: 'セ with dakuten: se becomes ze.',
  ゾ: 'ソ with dakuten: so becomes zo.',
  ダ: 'タ with dakuten: ta becomes da.',
  ヂ: 'チ with dakuten: chi becomes ji, the same sound as ジ. It\'s rare: ジ is the usual way to write ji.',
  ヅ: 'ツ with dakuten: tsu becomes zu, the same sound as ズ. It\'s rare: ズ is the usual way to write zu.',
  デ: 'テ with dakuten: te becomes de.',
  ド: 'ト with dakuten: to becomes do.',
  バ: 'ハ with dakuten: ha becomes ba.',
  ビ: 'ヒ with dakuten: hi becomes bi.',
  ブ: 'フ with dakuten: fu becomes bu.',
  ベ: 'ヘ with dakuten: he becomes be.',
  ボ: 'ホ with dakuten: ho becomes bo.',
  パ: 'ハ with handakuten, the little circle (゜) that turns h into p: ha becomes pa.',
  ピ: 'ヒ with the little circle: hi becomes pi.',
  プ: 'フ with the little circle: fu becomes pu.',
  ペ: 'ヘ with the little circle: he becomes pe.',
  ポ: 'ホ with the little circle: ho becomes po.',
  // Katakana yōon
  キャ: 'キ with a small ャ: ki and ya run together into one sound, kya.',
  キュ: 'キ with a small ュ: ki and yu run together into one sound, kyu.',
  キョ: 'キ with a small ョ: ki and yo run together into one sound, kyo.',
  シャ: 'シ with a small ャ: shi and ya run together into one sound, sha.',
  シュ: 'シ with a small ュ: shi and yu run together into one sound, shu.',
  ショ: 'シ with a small ョ: shi and yo run together into one sound, sho.',
  チャ: 'チ with a small ャ: chi and ya run together into one sound, cha.',
  チュ: 'チ with a small ュ: chi and yu run together into one sound, chu.',
  チョ: 'チ with a small ョ: chi and yo run together into one sound, cho.',
  ニャ: 'ニ with a small ャ: ni and ya run together into one sound, nya.',
  ニュ: 'ニ with a small ュ: ni and yu run together into one sound, nyu.',
  ニョ: 'ニ with a small ョ: ni and yo run together into one sound, nyo.',
  ヒャ: 'ヒ with a small ャ: hi and ya run together into one sound, hya.',
  ヒュ: 'ヒ with a small ュ: hi and yu run together into one sound, hyu.',
  ヒョ: 'ヒ with a small ョ: hi and yo run together into one sound, hyo.',
  ミャ: 'ミ with a small ャ: mi and ya run together into one sound, mya.',
  ミュ: 'ミ with a small ュ: mi and yu run together into one sound, myu.',
  ミョ: 'ミ with a small ョ: mi and yo run together into one sound, myo.',
  リャ: 'リ with a small ャ: ri and ya run together into one sound, rya.',
  リュ: 'リ with a small ュ: ri and yu run together into one sound, ryu.',
  リョ: 'リ with a small ョ: ri and yo run together into one sound, ryo.',
  ギャ: 'ギ with a small ャ: gi and ya run together into one sound, gya.',
  ギュ: 'ギ with a small ュ: gi and yu run together into one sound, gyu.',
  ギョ: 'ギ with a small ョ: gi and yo run together into one sound, gyo.',
  ジャ: 'ジ with a small ャ: ji and ya run together into one sound, ja.',
  ジュ: 'ジ with a small ュ: ji and yu run together into one sound, ju.',
  ジョ: 'ジ with a small ョ: ji and yo run together into one sound, jo.',
  ビャ: 'ビ with a small ャ: bi and ya run together into one sound, bya.',
  ビュ: 'ビ with a small ュ: bi and yu run together into one sound, byu.',
  ビョ: 'ビ with a small ョ: bi and yo run together into one sound, byo.',
  ピャ: 'ピ with a small ャ: pi and ya run together into one sound, pya.',
  ピュ: 'ピ with a small ュ: pi and yu run together into one sound, pyu.',
  ピョ: 'ピ with a small ョ: pi and yo run together into one sound, pyo.',
};

// The memory tip for a kana, or null if there isn't one.
export function kanaTip(char: string): string | null {
  return KANA_TIPS[char] ?? null;
}
