// A memory tip for every kana: a picture of its shape tied to its sound.
// These are first drafts, meant to be rewritten in the app's own voice.

const KANA_TIPS: Readonly<Record<string, string>> = {
  // Hiragana
  あ: 'A cross with a big loop swung around it, like an acrobat mid-flip shouting "ah!": a.',
  い: 'Two short strokes standing side by side, like two eels: i.',
  う: 'A small dash over a hooked back, like someone doubled over going "ooh": u.',
  え: 'A dash over a zig-zag that kicks out at the bottom, like someone tripping and saying "eh?": e.',
  お: 'Like あ with an extra dash flying off to the right, an "oh!" of surprise: o.',
  か: 'A bent blade with a small stroke beside it, like a karate chop: ka.',
  き: 'Two crossbars on a stem with a curl at the bottom, like an old key: ki.',
  く: 'One sharp bend, like a cuckoo opening its beak: ku.',
  け: 'A tall line with a cross beside it, like a keg with a tap: ke.',
  こ: 'Two short strokes stacked, like two coins lying flat: ko.',
  さ: 'A crossbar and a stroke through it, with a curve at the bottom like a hanging saddle: sa.',
  し: 'One stroke that dips and curves up, like a fishing hook. She went fishing: shi.',
  す: 'A crossbar with a stroke that loops once and drops, like a swing: su.',
  せ: 'A crossbar on two posts, one bending back underneath, like a setting sun behind a fence: se.',
  そ: 'A zig, a zag and a long sweep, like a thread being sewn: so.',
  た: 'A cross next to two short strokes, like a table with two plates: ta.',
  ち: 'A crossbar with a curve bulging right, like the bottom of a 5 puffing out its cheek: chi.',
  つ: 'One wave curling over to the left, like a small tsunami: tsu.',
  て: 'A crossbar with a stroke curving down and back, like a tail hanging off a table: te.',
  と: 'A short tick leaning on a curve, like a splinter in a toe: to.',
  な: 'A cross on the left and a loop on the right, like a nun kneeling in prayer: na.',
  に: 'A tall line with two short strokes beside it, like a knee next to two steps: ni.',
  ぬ: 'Two crossing strokes ending in a little loop, like noodles curling on chopsticks: nu.',
  ね: 'A stem with a curve that ends in a loop, like a cat curling its tail. Neko means cat: ne.',
  の: 'One big swirl, like the circle on a "no entry" sign: no.',
  は: 'A tall line with a cross and a loop, like someone holding their belly laughing "ha!": ha.',
  ひ: 'One wide curve, like a big grin going "hee hee": hi.',
  ふ: 'Four strokes around a peak, like Mount Fuji with clouds: fu.',
  へ: 'A simple peak, like a hill that makes you go "heh" when you climb it: he.',
  ほ: 'Like は with an extra bar on top, a taller laugh: "ho ho!": ho.',
  ま: 'Two crossbars on a stem that loops at the bottom, like a mast with a rope: ma.',
  み: 'A loop with a tail crossing it, like the number 21. Me at twenty-one: mi.',
  む: 'A stroke with a loop and a little dash, like a cow turning its head to moo: mu.',
  め: 'Like ぬ but with no loop, an open eye. Me means eye: me.',
  も: 'A fishing hook with two lines across it, for catching more fish: mo.',
  や: 'A curved horn with a line through it and a dot, like a yak: ya.',
  ゆ: 'A loop with a line through the middle, like a U-turn: yu.',
  よ: 'A cross with a loop at the bottom, like a yo-yo on its string: yo.',
  ら: 'A dash over a curve, like a rabbit with one ear up: ra.',
  り: 'Two strokes, the right one longer, like reeds by a river: ri.',
  る: 'A zig-zag that ends in a loop, like a road that loops back home. Route: ru.',
  れ: 'A stem with a tail kicking out to the right, like a ray swimming off: re.',
  ろ: 'Like る with no loop at the end, an open road: ro.',
  わ: 'A stem with a curve that rounds back in, like a duck waddling: wa.',
  を: 'A figure pulling back on reins, "whoa!": wo.',
  ん: 'Like a quickly written lowercase n with a tail: n.',

  // Katakana
  ア: 'A short stroke hooked over a long one, like an axe: a.',
  イ: 'A slash leaning on a pole, like an easel: i.',
  ウ: 'Like う with a roof on top, a hut to say "ooh" in: u.',
  エ: 'A steel girder, like the edge of an elevator shaft: e.',
  オ: 'A cross with a slash, like an oar in the water: o.',
  カ: 'Like か without its extra stroke, a karate chop: ka.',
  キ: 'Two crossbars on a stem, like a key: ki.',
  ク: 'A short tick and a long bent stroke, like a cuckoo bird\'s beak: ku.',
  ケ: 'A small slash, a crossbar and a long leg, like a K leaning over: ke.',
  コ: 'Three sides of a box, like a corner: ko.',
  サ: 'A crossbar on two posts, one bending down, like a saw: sa.',
  シ: 'Two short strokes on the left and a long one sweeping up, like a smile turned sideways. She smiles: shi.',
  ス: 'A bent stroke with a leg kicking out, like someone striding in a suit: su.',
  セ: 'Like せ with one post taken away: se.',
  ソ: 'A short stroke on top and a long one falling down, like sewing a stitch downward: so.',
  タ: 'Like ク with an extra line inside, a table set up in a tent: ta.',
  チ: 'A slanted cap over a cross, like a cheerleader\'s pom-pom stick: chi.',
  ツ: 'Short strokes on top and a long one sweeping down, like a tsunami crashing: tsu.',
  テ: 'A T with an extra bar on top, like a telephone pole: te.',
  ト: 'A pole with one branch, like a totem pole: to.',
  ナ: 'A cross whose down stroke bends left, like a knife: na.',
  ニ: 'Two lines, like two knees. 二 is also the number two: ni.',
  ヌ: 'Like フ with a small slash across it, noodles held by chopsticks: nu.',
  ネ: 'A little roof over a cross, like a net on a post: ne.',
  ノ: 'One slash, a firm "no!": no.',
  ハ: 'Two strokes spreading apart, like an open mouth laughing "ha!": ha.',
  ヒ: 'A line with a hook curving back, like the heel of a shoe: hi.',
  フ: 'One hooked stroke, like the slope of Mount Fuji: fu.',
  ヘ: 'The same peak as へ, a hill: he.',
  ホ: 'A cross with two little legs, like a holy cross on a stand: ho.',
  マ: 'A stroke folding back with a tick inside, like a mama bird\'s wing: ma.',
  ミ: 'Three short lines, like three mice asleep in a row: mi.',
  ム: 'A triangle with a tail, like a cow\'s nose: mu.',
  メ: 'Two crossing strokes, like an X marks the spot. Meet me here: me.',
  モ: 'Like も without the curl, two lines on a hook for more fish: mo.',
  ヤ: 'Like や without the dot, a yak\'s horn: ya.',
  ユ: 'A U-shaped hook on a base, like a U-turn: yu.',
  ヨ: 'A backward E, like a yo-yo trick going the wrong way: yo.',
  ラ: 'A dash over a bent stroke, like a rabbit ear: ra.',
  リ: 'Like り, two reeds: ri.',
  ル: 'Two legs, the right one kicking up, like a runner: ru.',
  レ: 'One stroke down and a flick up to the right, like a check mark on a report: re.',
  ロ: 'A box, like a mouth wide open to roar: ro.',
  ワ: 'A roof curving down, like a wall of water: wa.',
  ヲ: 'Like フ with a bar across it, a horse pulling up: "whoa!": wo.',
  ン: 'A short stroke on the left and a long one sweeping up, like a nose sniffing upward: n.',
};

// The memory tip for a kana, or null if there isn't one.
export function kanaTip(char: string): string | null {
  return KANA_TIPS[char] ?? null;
}
