// Words for Word Forge: common words written only with kana the app teaches, with their
// meanings. None needs small っ or the long mark ー yet (the app doesn't teach those), and each
// word's romaji reads back as the same kana (both checked in words.test.ts).

export type Word = {
  text: string; // as written, in hiragana or katakana
  meaning: string;
  // The emoji for it. It names the picture shown on the card (see src/constants/word-pictures.ts).
  picture: string;
};

export const WORDS: readonly Word[] = [
  // Hiragana
  { text: 'あい', meaning: 'love', picture: '❤️' },
  { text: 'あお', meaning: 'blue', picture: '🔵' },
  { text: 'あか', meaning: 'red', picture: '🔴' },
  { text: 'あき', meaning: 'autumn', picture: '🍂' },
  { text: 'あさ', meaning: 'morning', picture: '🌅' },
  { text: 'あし', meaning: 'leg, foot', picture: '🦵' },
  { text: 'あめ', meaning: 'rain', picture: '🌧️' },
  { text: 'いえ', meaning: 'house', picture: '🏠' },
  { text: 'いけ', meaning: 'pond', picture: '🦆' },
  { text: 'いす', meaning: 'chair', picture: '🪑' },
  { text: 'いぬ', meaning: 'dog', picture: '🐶' },
  { text: 'いま', meaning: 'now', picture: '⏰' },
  { text: 'うえ', meaning: 'above', picture: '⬆️' },
  { text: 'うた', meaning: 'song', picture: '🎵' },
  { text: 'うみ', meaning: 'sea', picture: '🌊' },
  { text: 'えき', meaning: 'station', picture: '🚉' },
  { text: 'おに', meaning: 'ogre', picture: '👹' },
  { text: 'かお', meaning: 'face', picture: '😊' },
  { text: 'かさ', meaning: 'umbrella', picture: '☂️' },
  { text: 'かみ', meaning: 'paper, hair', picture: '📄' },
  { text: 'かわ', meaning: 'river', picture: '🛶' },
  { text: 'くち', meaning: 'mouth', picture: '👄' },
  { text: 'くも', meaning: 'cloud', picture: '☁️' },
  { text: 'くるま', meaning: 'car', picture: '🚗' },
  { text: 'こえ', meaning: 'voice', picture: '🗣️' },
  { text: 'ここ', meaning: 'here', picture: '📍' },
  { text: 'さかな', meaning: 'fish', picture: '🐟' },
  { text: 'しお', meaning: 'salt', picture: '🧂' },
  { text: 'した', meaning: 'below', picture: '⬇️' },
  { text: 'すし', meaning: 'sushi', picture: '🍣' },
  { text: 'そら', meaning: 'sky', picture: '🌤️' },
  { text: 'たこ', meaning: 'octopus', picture: '🐙' },
  { text: 'つき', meaning: 'moon', picture: '🌙' },
  { text: 'つくえ', meaning: 'desk', picture: '🖥️' },
  { text: 'とり', meaning: 'bird', picture: '🐦' },
  { text: 'なつ', meaning: 'summer', picture: '☀️' },
  { text: 'なまえ', meaning: 'name', picture: '📛' },
  { text: 'にく', meaning: 'meat', picture: '🍖' },
  { text: 'ねこ', meaning: 'cat', picture: '🐱' },
  { text: 'はな', meaning: 'flower, nose', picture: '🌸' },
  { text: 'はし', meaning: 'chopsticks, bridge', picture: '🥢' },
  { text: 'はる', meaning: 'spring', picture: '🌷' },
  { text: 'ひと', meaning: 'person', picture: '🧑' },
  { text: 'ふね', meaning: 'boat', picture: '⛵' },
  { text: 'ふゆ', meaning: 'winter', picture: '⛄' },
  { text: 'へや', meaning: 'room', picture: '🛏️' },
  { text: 'ほし', meaning: 'star', picture: '⭐' },
  { text: 'ほん', meaning: 'book', picture: '📖' },
  { text: 'みみ', meaning: 'ear', picture: '👂' },
  { text: 'むし', meaning: 'insect', picture: '🐛' },
  { text: 'もり', meaning: 'forest', picture: '🌲' },
  { text: 'やま', meaning: 'mountain', picture: '⛰️' },
  { text: 'ゆき', meaning: 'snow', picture: '❄️' },
  { text: 'よる', meaning: 'night', picture: '🌃' },
  { text: 'わに', meaning: 'crocodile', picture: '🐊' },
  { text: 'かぎ', meaning: 'key', picture: '🔑' },
  { text: 'かぜ', meaning: 'wind', picture: '🌬️' },
  { text: 'みず', meaning: 'water', picture: '💧' },
  { text: 'まど', meaning: 'window', picture: '🪟' },
  { text: 'ちず', meaning: 'map', picture: '🗺️' },
  { text: 'たまご', meaning: 'egg', picture: '🥚' },
  { text: 'りんご', meaning: 'apple', picture: '🍎' },
  { text: 'ごはん', meaning: 'rice, a meal', picture: '🍚' },
  { text: 'でんわ', meaning: 'telephone', picture: '☎️' },
  { text: 'にほん', meaning: 'Japan', picture: '🗾' },
  { text: 'にほんご', meaning: 'Japanese (the language)', picture: '💬' },
  { text: 'ひらがな', meaning: 'hiragana', picture: '✍️' },
  { text: 'かたかな', meaning: 'katakana', picture: '🔠' },
  { text: 'ともだち', meaning: 'friend', picture: '🤝' },
  { text: 'せんせい', meaning: 'teacher', picture: '🧑‍🏫' },
  { text: 'ありがとう', meaning: 'thank you', picture: '🙏' },
  { text: 'おはよう', meaning: 'good morning', picture: '🌞' },
  { text: 'すみません', meaning: 'excuse me, sorry', picture: '🙇' },
  { text: 'さんぽ', meaning: 'a walk', picture: '🚶' },
  { text: 'てんぷら', meaning: 'tempura', picture: '🍤' },
  { text: 'でんしゃ', meaning: 'train', picture: '🚃' },
  { text: 'しゃしん', meaning: 'photo', picture: '🖼️' },
  { text: 'いしゃ', meaning: 'doctor', picture: '🩺' },
  { text: 'おちゃ', meaning: 'tea', picture: '🍵' },
  { text: 'じしょ', meaning: 'dictionary', picture: '📕' },
  { text: 'きょう', meaning: 'today', picture: '📅' },
  { text: 'としょかん', meaning: 'library', picture: '🏛️' },
  { text: 'べんきょう', meaning: 'study', picture: '✏️' },
  { text: 'りょこう', meaning: 'travel', picture: '🧳' },
  { text: 'ひゃく', meaning: 'hundred', picture: '💯' },
  { text: 'きんぎょ', meaning: 'goldfish', picture: '🐠' },

  // Katakana
  { text: 'カメラ', meaning: 'camera', picture: '📷' },
  { text: 'テレビ', meaning: 'TV', picture: '📺' },
  { text: 'ラジオ', meaning: 'radio', picture: '📻' },
  { text: 'ピアノ', meaning: 'piano', picture: '🎹' },
  { text: 'トマト', meaning: 'tomato', picture: '🍅' },
  { text: 'バナナ', meaning: 'banana', picture: '🍌' },
  { text: 'メロン', meaning: 'melon', picture: '🍈' },
  { text: 'レモン', meaning: 'lemon', picture: '🍋' },
  { text: 'パン', meaning: 'bread', picture: '🍞' },
  { text: 'ペン', meaning: 'pen', picture: '🖊️' },
  { text: 'ホテル', meaning: 'hotel', picture: '🏨' },
  { text: 'アメリカ', meaning: 'America', picture: '🗽' },
  { text: 'カナダ', meaning: 'Canada', picture: '🍁' },
  { text: 'イギリス', meaning: 'the UK', picture: '💂' },
  { text: 'ドイツ', meaning: 'Germany', picture: '🥨' },
  { text: 'ロシア', meaning: 'Russia', picture: '🪆' },
  { text: 'パンダ', meaning: 'panda', picture: '🐼' },
  { text: 'ライオン', meaning: 'lion', picture: '🦁' },
  { text: 'キリン', meaning: 'giraffe', picture: '🦒' },
  { text: 'ゴリラ', meaning: 'gorilla', picture: '🦍' },
  { text: 'ナイフ', meaning: 'knife', picture: '🔪' },
  { text: 'テニス', meaning: 'tennis', picture: '🎾' },
  { text: 'ゴルフ', meaning: 'golf', picture: '⛳' },
  { text: 'ピザ', meaning: 'pizza', picture: '🍕' },
  { text: 'パスタ', meaning: 'pasta', picture: '🍝' },
  { text: 'ハム', meaning: 'ham', picture: '🥓' },
  { text: 'チキン', meaning: 'chicken', picture: '🍗' },
  { text: 'ミルク', meaning: 'milk', picture: '🥛' },
  { text: 'ドア', meaning: 'door', picture: '🚪' },
  { text: 'ベンチ', meaning: 'bench', picture: '🏞️' },
  { text: 'リボン', meaning: 'ribbon', picture: '🎀' },
  { text: 'アニメ', meaning: 'anime', picture: '🎬' },
  { text: 'マンガ', meaning: 'manga', picture: '📚' },
  { text: 'カラオケ', meaning: 'karaoke', picture: '🎤' },
  { text: 'シャツ', meaning: 'shirt', picture: '👕' },
  { text: 'ジャム', meaning: 'jam', picture: '🍓' },
];
