// Words for Word Forge: common words written only with kana the app teaches, with their
// meanings. None needs small っ or the long mark ー yet (the app doesn't teach those), and each
// word's romaji reads back as the same kana (both checked in words.test.ts).

export type Word = {
  text: string; // as written, in hiragana or katakana
  meaning: string;
};

export const WORDS: readonly Word[] = [
  // Hiragana
  { text: 'あい', meaning: 'love' },
  { text: 'あお', meaning: 'blue' },
  { text: 'あか', meaning: 'red' },
  { text: 'あき', meaning: 'autumn' },
  { text: 'あさ', meaning: 'morning' },
  { text: 'あし', meaning: 'leg, foot' },
  { text: 'あめ', meaning: 'rain' },
  { text: 'いえ', meaning: 'house' },
  { text: 'いけ', meaning: 'pond' },
  { text: 'いす', meaning: 'chair' },
  { text: 'いぬ', meaning: 'dog' },
  { text: 'いま', meaning: 'now' },
  { text: 'うえ', meaning: 'above' },
  { text: 'うた', meaning: 'song' },
  { text: 'うみ', meaning: 'sea' },
  { text: 'えき', meaning: 'station' },
  { text: 'おに', meaning: 'ogre' },
  { text: 'かお', meaning: 'face' },
  { text: 'かさ', meaning: 'umbrella' },
  { text: 'かみ', meaning: 'paper, hair' },
  { text: 'かわ', meaning: 'river' },
  { text: 'くち', meaning: 'mouth' },
  { text: 'くも', meaning: 'cloud' },
  { text: 'くるま', meaning: 'car' },
  { text: 'こえ', meaning: 'voice' },
  { text: 'ここ', meaning: 'here' },
  { text: 'さかな', meaning: 'fish' },
  { text: 'しお', meaning: 'salt' },
  { text: 'した', meaning: 'below' },
  { text: 'すし', meaning: 'sushi' },
  { text: 'そら', meaning: 'sky' },
  { text: 'たこ', meaning: 'octopus' },
  { text: 'つき', meaning: 'moon' },
  { text: 'つくえ', meaning: 'desk' },
  { text: 'とり', meaning: 'bird' },
  { text: 'なつ', meaning: 'summer' },
  { text: 'なまえ', meaning: 'name' },
  { text: 'にく', meaning: 'meat' },
  { text: 'ねこ', meaning: 'cat' },
  { text: 'はな', meaning: 'flower, nose' },
  { text: 'はし', meaning: 'chopsticks, bridge' },
  { text: 'はる', meaning: 'spring' },
  { text: 'ひと', meaning: 'person' },
  { text: 'ふね', meaning: 'boat' },
  { text: 'ふゆ', meaning: 'winter' },
  { text: 'へや', meaning: 'room' },
  { text: 'ほし', meaning: 'star' },
  { text: 'ほん', meaning: 'book' },
  { text: 'みみ', meaning: 'ear' },
  { text: 'むし', meaning: 'insect' },
  { text: 'もり', meaning: 'forest' },
  { text: 'やま', meaning: 'mountain' },
  { text: 'ゆき', meaning: 'snow' },
  { text: 'よる', meaning: 'night' },
  { text: 'わに', meaning: 'crocodile' },
  { text: 'かぎ', meaning: 'key' },
  { text: 'かぜ', meaning: 'wind' },
  { text: 'みず', meaning: 'water' },
  { text: 'まど', meaning: 'window' },
  { text: 'ちず', meaning: 'map' },
  { text: 'たまご', meaning: 'egg' },
  { text: 'りんご', meaning: 'apple' },
  { text: 'ごはん', meaning: 'rice, a meal' },
  { text: 'でんわ', meaning: 'telephone' },
  { text: 'にほん', meaning: 'Japan' },
  { text: 'にほんご', meaning: 'Japanese (the language)' },
  { text: 'ひらがな', meaning: 'hiragana' },
  { text: 'かたかな', meaning: 'katakana' },
  { text: 'ともだち', meaning: 'friend' },
  { text: 'せんせい', meaning: 'teacher' },
  { text: 'ありがとう', meaning: 'thank you' },
  { text: 'おはよう', meaning: 'good morning' },
  { text: 'すみません', meaning: 'excuse me, sorry' },
  { text: 'さんぽ', meaning: 'a walk' },
  { text: 'てんぷら', meaning: 'tempura' },
  { text: 'でんしゃ', meaning: 'train' },
  { text: 'しゃしん', meaning: 'photo' },
  { text: 'いしゃ', meaning: 'doctor' },
  { text: 'おちゃ', meaning: 'tea' },
  { text: 'じしょ', meaning: 'dictionary' },
  { text: 'きょう', meaning: 'today' },
  { text: 'としょかん', meaning: 'library' },
  { text: 'べんきょう', meaning: 'study' },
  { text: 'りょこう', meaning: 'travel' },
  { text: 'ひゃく', meaning: 'hundred' },
  { text: 'きんぎょ', meaning: 'goldfish' },

  // Katakana
  { text: 'カメラ', meaning: 'camera' },
  { text: 'テレビ', meaning: 'TV' },
  { text: 'ラジオ', meaning: 'radio' },
  { text: 'ピアノ', meaning: 'piano' },
  { text: 'トマト', meaning: 'tomato' },
  { text: 'バナナ', meaning: 'banana' },
  { text: 'メロン', meaning: 'melon' },
  { text: 'レモン', meaning: 'lemon' },
  { text: 'パン', meaning: 'bread' },
  { text: 'ペン', meaning: 'pen' },
  { text: 'ホテル', meaning: 'hotel' },
  { text: 'アメリカ', meaning: 'America' },
  { text: 'カナダ', meaning: 'Canada' },
  { text: 'イギリス', meaning: 'the UK' },
  { text: 'ドイツ', meaning: 'Germany' },
  { text: 'ロシア', meaning: 'Russia' },
  { text: 'パンダ', meaning: 'panda' },
  { text: 'ライオン', meaning: 'lion' },
  { text: 'キリン', meaning: 'giraffe' },
  { text: 'ゴリラ', meaning: 'gorilla' },
  { text: 'ナイフ', meaning: 'knife' },
  { text: 'テニス', meaning: 'tennis' },
  { text: 'ゴルフ', meaning: 'golf' },
  { text: 'ピザ', meaning: 'pizza' },
  { text: 'パスタ', meaning: 'pasta' },
  { text: 'ハム', meaning: 'ham' },
  { text: 'チキン', meaning: 'chicken' },
  { text: 'ミルク', meaning: 'milk' },
  { text: 'ドア', meaning: 'door' },
  { text: 'ベンチ', meaning: 'bench' },
  { text: 'リボン', meaning: 'ribbon' },
  { text: 'アニメ', meaning: 'anime' },
  { text: 'マンガ', meaning: 'manga' },
  { text: 'カラオケ', meaning: 'karaoke' },
  { text: 'シャツ', meaning: 'shirt' },
  { text: 'ジャム', meaning: 'jam' },
];
